//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace Model
{
    // Clase de contexto de Entity Framework para la base de datos.
    public class Model1 : DbContext
    {
        public DbSet<Actividad> Actividad { get; set; }
        public DbSet<Socio> Socio { get; set; }
        public DbSet<Reserva> Reserva { get; set; }

        // Puedes agregar un constructor si necesitas una cadena de conexión específica.
        // public Model1() : base("name=TuCadenaDeConexion") { }
    }
}

